name: test-and-publish
on:
  push:
    branches:
      - develop

jobs:
  openergy:
    uses: openergy/ogithub-actions/.github/workflows/opypackage-standard-v05.yml@master
    with:
      publish-to-pypi: true
      install-eplus-2210: true
      check-documentation: true
      os-requirements: "['ubuntu-latest']"
      python-conda-requirement: ">=3.8,<3.13"
      python-test-versions: "['3.11', '3.12']"

    secrets:
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
